name: Testing the action

on: 
  push:
    paths: hello-world-docker-action/**
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Run container action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '${{ github.actor }}'

      - name: Output
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
